Autorisation
Nazari-Adamenko/project_news_front pull request #2
Opened 2022-06-15 08:32 UTC by Nazari-Adamenko

2022-06-15 10:01 UTC, ekaterinagaltsova commented on src/redux/actions/index.js
> +  type: actionTypes.GET_MODAL,
toggleModal?

2022-06-15 10:02 UTC, ekaterinagaltsova commented on src/redux/reducers/rootReducer.js
> +  modal: authReducer,
может лучше auth?

2022-06-15 10:04 UTC, ekaterinagaltsova commented on src/App.jsx
> +        <ModalAuth />
либо ModalOfAuth, либо AuthModal

2022-06-15 10:05 UTC, ekaterinagaltsova commented on src/components/ButtonAuthGroup/ButtonAuthGroup.jsx
> +function ButtonAuthGroup({ name, openModal }) {
нет тут группы - одна кнопочка

2022-06-15 10:07 UTC, ekaterinagaltsova commented on src/components/ButtonAuthGroup/ButtonAuthGroup.jsx
> +    <Button type="button" onClick={() => openModal(name)} className="btn btn-primary me-1">{name}</Button>
очень длинная строка

2022-06-15 10:11 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +  const registrationUser = (event) => {
диспатчишь для регистрации событие?

2022-06-15 10:11 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +  const validate = yup.object({
вынести в хелпер

2022-06-15 10:11 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +    <Formik
формик внутри модалки

2022-06-15 10:13 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +        <Modal.Header closeButton>
может деструктурировать  Header, Title, Body и Footer из Modal?

2022-06-15 10:14 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +            {isAuth && <TextField label="Confirm Password" name="confirmPassword" type="password" placeholder="Repeat password" />}
пропсы в столбик

2022-06-15 10:15 UTC, ekaterinagaltsova commented on src/components/TextField/TextField.jsx
> +export default function TextField({ label, ...props }) {
оберни в мемо

2022-06-15 10:15 UTC, ekaterinagaltsova commented on src/components/Spinner/Spinner.jsx
>  function Spinner() {
ммемо где?

2022-06-15 10:16 UTC, ekaterinagaltsova commented on src/pages/MainPage/MainPage.jsx
> +        id, title, content, tag, userId,
ну такое

2022-06-15 10:18 UTC, ekaterinagaltsova commented on src/redux/actions/index.js
> +  type: actionTypes.USER_REGISTRATION,
AUTH_REQUESTED?

2022-06-15 10:20 UTC, ekaterinagaltsova commented on src/redux/reducers/authReducer.js
> +  user: [],
может пустой объект?

2022-06-15 10:21 UTC, ekaterinagaltsova commented on src/redux/reducers/authReducer.js
> +  isFetching: '',
false?

2022-06-15 10:21 UTC, ekaterinagaltsova commented on src/redux/reducers/authReducer.js
> +  error: '',
null

2022-06-15 10:21 UTC, ekaterinagaltsova commented on src/redux/reducers/authReducer.js
> +    case USER_AUTOROTATION:
?

2022-06-15 10:23 UTC, ekaterinagaltsova commented on src/redux/sagas/authSaga.js
> +import { gotUsers, cannotBedRequest } from '../actions';
bed = кровать

2022-06-15 10:26 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +import Image from 'react-bootstrap/Image';
импорт бутстрапа сделай единообразным

2022-06-15 10:27 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
>  import ButtonAuthGroup from '../ButtonAuthGroup/ButtonAuthGroup';
пустая строка перед своими

2022-06-15 10:27 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +import { getModal, destroyUser } from '../../redux/actions';
у нас нет по ТЗ удаления юзера

2022-06-15 10:30 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +  const errorAuth = useSelector((state) => state.auth.error);
нейминг поправь

2022-06-15 10:31 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +        isAuth
зачем тернарник?

2022-06-15 10:32 UTC, ekaterinagaltsova commented on src/components/ModalAuth/ModalAuth.jsx
> +      onSubmit={initializationUser}
userInitialization (но это не точно)

2022-06-16 07:12 UTC, s-skubedin requested changes

2022-06-16 07:12 UTC, s-skubedin commented on src/components/Header/Header.jsx
> +                  <Button onClick={() => openModal('Sign Up')}>Sign Up</Button>
Строки должны быть в константе и использоваться по всему коду

2022-06-16 07:12 UTC, s-skubedin commented on src/components/ModalAuth/ModalAuth.jsx
> +  const isAuth = typeModal === 'Sign Up';
Строка в константе

2022-06-16 07:12 UTC, s-skubedin commented on src/components/ModalAuth/ModalAuth.jsx
> +            }
initial value вынести в константу

2022-06-16 07:12 UTC, s-skubedin commented on src/components/TextField/TextField.jsx
> +        // eslint-disable-next-line react/jsx-props-no-spreading
Все верно, исправь

2022-06-16 07:12 UTC, s-skubedin commented on src/helpers/validate.js
> +    .required('Confirm password is require'),
Объект вынеси в константу

2022-06-16 07:12 UTC, s-skubedin commented on src/helpers/validate.js
> +    .required('Password is required'),
Объект вынеси в константу

2022-06-16 07:12 UTC, s-skubedin commented on src/helpers/validate.js
> +    .min(6, 'Password must be at least 6 characters')
Числа, как и строки должны быть в константе

2022-06-16 07:12 UTC, s-skubedin commented on src/redux/sagas/authSaga.js
> +  const choiceOfPath = typeModal.auth.typeModal === 'Sign Up' ? '/users' : '/users/sign_in';
Зачем это?

2022-06-16 09:26 UTC, s-skubedin commented on src/components/ModalAuth/ModalAuth.jsx
> +    };
Смысла в этом нет. Что до этого создавался объект на каждый рендер, что сейчас создается.
Вынеси за компонент

2022-06-16 09:26 UTC, s-skubedin commented on src/helpers/validate.js
> +    .required(MESSAGE_CONFIRM_PASSWORD_REQUIRE),
Объект не вынес

2022-06-16 09:26 UTC, s-skubedin commented on src/redux/actions/index.js
>  // это action creator - эти функции возвращают объект, который нужно запихать в диспатч
Круто, информативно.. Но зачем?? Удали

2022-06-16 10:57 UTC, merged