User page
Nazari-Adamenko/project_news_front pull request #5
Opened 2022-06-22 11:10 UTC by Nazari-Adamenko

2022-06-23 10:22 UTC, ekaterinagaltsova commented on src/constants.js
> +export const ROUT_PATH_MAIN = '/';
MAIN ROUTE?

2022-06-23 10:25 UTC, ekaterinagaltsova commented on src/pages/MainPage.jsx
> +  const { posts } = useSelector((state) => state.posts);
const posts = useSelector((state) => state.posts.posts);

2022-06-23 10:27 UTC, ekaterinagaltsova commented on src/redux/reducers/rootReducer.js
>  import authReducer from './authReducer';
+ empty line

2022-06-23 10:28 UTC, ekaterinagaltsova commented on src/redux/reducers/userReducer.js
> +  dataUser: {},
если это данные пользователя - то userData

2022-06-23 10:31 UTC, ekaterinagaltsova commented on src/redux/sagas/loggedOutSaga.js
> +const validateStatusRequest = 'OK';
это имя функции - а хотел хардкордную константу?

2022-06-23 10:58 UTC, ekaterinagaltsova commented
.env в удаленном репо не должно быть

2022-06-24 06:48 UTC, s-skubedin requested changes
Исправь замечания Екатерины!

2022-06-24 06:48 UTC, s-skubedin commented on src/pages/MainPage.jsx
> +      {typeof posts !== 'string'
Делай проверку на массив..
Почему posts строка?
Логика должна быть разделена, posts - массив, всегда массив... или null
Строка должна быть записана в другую переменную, названная в соответсвии с содержимым

2022-06-24 06:48 UTC, s-skubedin commented on src/pages/NotFoundPage.jsx
> +export default function NotFoundPage() {
Я уже писал ранее! Используй memo

2022-06-24 06:48 UTC, s-skubedin commented on src/pages/UserPage/UserPage.jsx
> +import Button from 'react-bootstrap/Button';
Импорты должны быть отсортированы согласно правилам eslint или prettier

2022-06-24 06:48 UTC, s-skubedin commented on src/pages/UserPage/UserPage.jsx
> +          : <div className="text-center h1 w-100">Not news</div>}
В двух местах используется одинаковый код, дублирование кода. Вынеси в один компонент и используй его

2022-06-24 06:48 UTC, s-skubedin commented on src/pages/UserPage/UserPage.jsx
> +        <div className="data-user__avatar">{ }</div>
Зачем пробел?

2022-06-24 06:48 UTC, s-skubedin commented on src/redux/actions/index.js
> +});
Конструкция action = type и payload, а не type и error. Исправь

2022-06-24 06:48 UTC, s-skubedin commented on src/redux/sagas/loggedOutSaga.js
> +    if (data.statusText === validateStatusRequest) {
Если пользователь хочет разлогиниться, то не надо ему препятствовать, даже если сервер лежит. Доступ к сайту (то есть токен) удаляется всегда

2022-06-24 06:48 UTC, s-skubedin commented on src/redux/sagas/userSaga.js
> +    yield put(gotDataUser(data));
Все названия в инфинитиве

2022-06-24 06:48 UTC, s-skubedin commented on src/redux/sagas/userSaga.js
> +    : `${ROUT_PATH_USERS}${value.id}`;
Если это логика для получения профиля и данных другого пользователя, то это разные саги. Исправь

2022-06-24 07:19 UTC, Nazari-Adamenko commented on src/pages/UserPage/UserPage.jsx
> +import Button from 'react-bootstrap/Button';
Иморты организованы согласно требованиям текущего проекта

2022-06-24 07:52 UTC, Nazari-Adamenko commented on src/redux/actions/index.js
> +});
Это из типовых ошибок, используйте сигнатуру action = {type, payload, error}. не нужно добавлять больше свойств.

2022-06-27 07:20 UTC, merged