Create news by user
Nazari-Adamenko/project_news_front pull request #6
Opened 2022-06-29 08:19 UTC by Nazari-Adamenko

2022-06-29 08:20 UTC, ekaterinagaltsova commented on src/components/CreatePost/CreatePost.jsx
> +    console.log(data);
-

2022-06-29 08:21 UTC, ekaterinagaltsova commented on src/components/CreatePost/CreatePost.jsx
> +  const isOpenModal = useSelector((state) => state.createNews.isShowCreateNews);
isShowCreateNews  - это Показать Создать Новости ?)

2022-06-29 08:22 UTC, ekaterinagaltsova commented on src/components/CreatePost/CreatePost.jsx
> +import { Formik, Form } from 'formik';
вверх

2022-06-29 08:23 UTC, ekaterinagaltsova commented on src/components/CreatePost/CreatePost.jsx
> +            <InputGroup className="flex-column">
группа из одного?

2022-06-29 08:23 UTC, ekaterinagaltsova commented on src/components/CreatePost/CreatePost.jsx
> +                onChange={(event) => { initialValue.content = event.target.value; }}
вынеси

2022-06-29 08:28 UTC, ekaterinagaltsova commented on src/components/ShowPosts/ShowPosts.jsx
> +  props: shape({}),
props?

2022-06-29 08:33 UTC, ekaterinagaltsova commented on src/redux/actions/index.js
> +export const callNewsCreationPage = (payload) => ({
просто открыть модалку?

2022-06-29 09:38 UTC, ekaterinagaltsova commented on .gitignore
>  yarn-error.log*
ты же не юзишь ярн

2022-06-29 09:39 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +    navigate(`${ROUT_TO_USER}/${ROUT_TO_AUTH_USER}`);
сложнаааа - не понятно - по отдельности они используются?

2022-06-29 09:40 UTC, ekaterinagaltsova commented on src/components/Layout/Layout.jsx
> +          <CreatePost />
как понять. - что это модалка?

2022-06-29 09:42 UTC, ekaterinagaltsova commented on src/pages/MainPage.jsx
> +      {posts !== null
задай при инициализаии не null - а пустой массив и проверяй на длину

2022-06-29 09:50 UTC, ekaterinagaltsova commented on src/pages/UserPage/UserPage.jsx
> +  const userAuthId = useSelector((state) => state.auth.authUser);
просто айди кого-то крутого?

2022-06-29 09:51 UTC, ekaterinagaltsova commented on src/pages/UserPage/UserPage.jsx
> +  const userData = useSelector((state) => state.dataUser.userData);
а тут весь юзер, но не такой крутой?

2022-06-29 13:15 UTC, Nazari-Adamenko commented on src/pages/MainPage.jsx
> +      {posts !== null
Это заначение мне приходит с бека

2022-06-29 14:42 UTC, ekaterinagaltsova commented on src/components/CreatePostModal/CreatePostModal.jsx
>      dispatch(cannotCreatePost(null));
-

2022-06-29 14:43 UTC, ekaterinagaltsova commented on src/components/CreatePostModal/CreatePostModal.jsx
>          <Modal.Title id="contained-modal-title-vcenter">
?

2022-06-29 14:49 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +  const authUser = useSelector((state) => state.dataUser.userData);
currentUser

2022-06-29 14:53 UTC, ekaterinagaltsova commented on src/components/ShowPosts/ShowPosts.jsx
> +  props: {},
posts!!!!!!!!!!!!

2022-06-29 14:58 UTC, ekaterinagaltsova commented on src/pages/UserPage/UserPage.jsx
> +  const initialButtonBar = userData.id === authUser.id;
is....

2022-06-29 15:00 UTC, ekaterinagaltsova commented on src/pages/UserPage/UserPage.jsx
> +        {isFetching
лучше безобразно, но единообразно

2022-07-01 07:31 UTC, s-skubedin requested changes

2022-07-01 07:31 UTC, s-skubedin commented on src/components/CreatePostModal/CreatePostModal.jsx
> +  } = Modal;
Должно деструктуризироваться из import

2022-07-04 08:10 UTC, merged